name: panvimdoc
on: [push]
jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Create Docs 📚
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: gitlab.nvim
          # The following are all optional
          pandoc: "README.md" # Input pandoc file
          toc: true # Table of contents
          description: "" # Project description used in title (if empty, uses neovim version and current date)
          demojify: false # Strip emojis from the vimdoc
          dedupsubheadings: true # Add heading to subheading anchor links to ensure that subheadings are unique
          treesitter: true # Use treesitter for highlighting codeblocks
          ignorerawblocks: true # Ignore raw html blocks in markdown when converting to vimdoc
          docmapping: false # Use h4 headers as mapping docs
          docmappingprojectname: false # Use project name in tag when writing mapping docs
          shiftheadinglevelby: 0 # Shift heading levels by specified number
          incrementheadinglevelby: 0 # Increment heading levels by specified number
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
