name: panvimdoc
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  docs:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    name: Create Docs 📚
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: gitlab.nvim
          pandoc: "README.md" 
          toc: true 
          description: "Create, review, and manage Gitlab reources without leaving Neovim"
          demojify: false 
          dedupsubheadings: false 
          treesitter: true 
          ignorerawblocks: true 
          docmapping: false 
          docmappingprojectname: false 
          shiftheadinglevelby: 0 
          incrementheadinglevelby: 0 
      - uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: gitlab.nvim.api
          pandoc: "API.md" 
          toc: true 
          demojify: false 
          dedupsubheadings: false 
          treesitter: true 
          ignorerawblocks: true 
          docmapping: false 
          docmappingprojectname: false 
          shiftheadinglevelby: 0 
          incrementheadinglevelby: 0 
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
